### libraries
library(SummarizedExperiment)
library(readxl)
library(tidyverse)
library(reshape2)
library(magrittr)
library(arsenal)
library(gapminder)
library(writexl)
library(corrplot)
library(ggpubr)
library(egg)
library(forcats)
library(FactoMineR)
library(factoextra)
library(caret)
library(amap)
library(pheatmap)
library(ComplexHeatmap)
library(cluster)
library(viridis)  #magma(), plasma(), inferno(), cividis(), mako(), rocket(), turbo()
library(rcartocolor) # display_carto_all(colorblind_friendly = TRUE) ; carto_pal(n = NULL, 'Safe')
library(rstatix)
library(data.table)
library(jtools)
library(sjPlot)
library(sjmisc)
library(vegan)
library(gtsummary)

